### ISSUE TITLE
Add Glint extension to package?

### ISSUE THREAD

**Issue by IgnaceMaes** [ember-tooling/vscode-ember-pack#8]
Can the [Glint VS Code](https://marketplace.visualstudio.com/items?itemName=typed-ember.glint-vscode) extension be added to the pack?

It would make the extension more discoverable.

**Comment by evoactivity** [comment]
I debated adding glint to the extension pack because of the need to turn of typescript for it to work optimally.

I think I'd be more open to adding glint once typescript support in Ember fully lands (nothing using the DT types, looking at you Ember Data!) but I could be convinced otherwise.

**Comment by IgnaceMaes** [comment]
Good point, that makes sense!

I just noticed now on the [Ember website](https://guides.emberjs.com/release/code-editors/#toc_typed-glimmer-templates) it's mentioned as well with a note that Glint isn't included in the pack.

Having that mention in this extension's VS Code marketplace description would also solve the discoverability point to me, so that could be a good middle ground for now?

**Comment by evoactivity** [comment]
> Having that mention in this extension's VS Code marketplace description 

Good idea, happy to take a PR for it if I don't get to it in the next few days.

**Comment by evoactivity** [comment]
Thanks for the PR @IgnaceMaes 💯 👍
